### ISSUE TITLE
Expand the use of app and service standard labels for filtering and Datadog monitoring

### ISSUE THREAD

**Issue by djfarrelly** [bufferapp/helm-chart-base-templates#1]
Hey @hharnisc, I had a couples ideas when thinking about your web service chart in the spirit of standardization...

We've used the `service` label a bit which has helped teams like Analyze filter their pods more easily and group them together. `k get po -l app=analytics`. We could make `app` and `service ` configurable and usable by the team.

https://github.com/bufferapp/helm-chart-base-templates/blob/666c2e1c964da67a7caa30719a2c1b723467a7d4/buffer-service/templates/deployment.yaml#L5-L9

Additionally, one pattern we've used in tandem with Datadog tags is to utilize the `app` and `service` labels as tags in our metrics. Since we've already forked the connect middleware library to our own variant, I think we could use these two values from a `values.yaml` to inject extra environment variables that could be used automatically in our Datadog library/middleware.

Instead of doing this...
```js
app.use(connectDatadog({
  tags: ['app:analyze', 'service:web'],
}, 'dd-agent.default'));
```

We could add the labels as environment variables via this helm chart...
```yaml
  env:
{{ toYaml .Values.env | indent 12 }}
{{- if .Values.labels.app }}
    - name: K8S_APP
      value: {{ .Values.labels.app }}
{{- end }}
{{- if .Values.labels.service }}
    - name: K8S_SERVICE
      value: {{ .Values.labels.service }}
{{- end }}
{{- if .Values.labels.track }}
    - name: K8S_TRACK
      value: {{ .Values.labels.track }}
{{- end }}
```

Then our [`connectDatadog`](https://github.com/bufferapp/node-connect-datadog/blob/b58760f65fc4d48fbd0de8ac2ff4dcbfe94eb76c/lib/index.js#L15) function could look for these environment variables and automatically add them!

```js
const standardTags = ['APP', 'SERVICE', 'TRACK']
  .map(t => process.env[`K8S_${t}`] && `${t.toLowerCase()}:${process.env[`K8S_${t}`]}`)
  .filter(t => !!t)
const tags = standardTags.concat(options.tags || [])
//...
```

Our config code then becomes:
```js
app.use(connectDatadog({}, 'dd-agent.default'));
```

https://github.com/bufferapp/buffer-analyze/blob/35e16cd4e53cbd25df53dde095f91c4fa7fc51b5/packages/server/index.js#L37-L41

What do you think?

For reference:
[Paper - Kubernetes Standardizing: Labels](https://paper.dropbox.com/doc/Kubernetes-Standardizing-Labels-XjHbHKXalxcH162A3F2Wa)
[Paper - Kubernetes Standardizing: Deployments](https://paper.dropbox.com/doc/Kubernetes-Standardizing-Deployments-Naming-and-Configuration-Management-wOEdyl16zIWBSgUzKP3uj)
[Paper - Datadog Monitoring Spec: Web servers / backends](https://paper.dropbox.com/doc/Monitoring-Spec-Web-servers-backends-feVsLQHY9RGInyhjZHu3y)
